// Auto-generated by scripts/generate-projects.mjs
// Run: node scripts/generate-projects.mjs

export interface Project {
  id: number;
  slug: string;
  title: string;
  category: 'Design' | 'Illustration';
  description: string;
  images: string[];
}

export const projects: Project[] = [
  {
    "id": 1,
    "slug": "bachelorproject-supernaturalis",
    "title": "Bachelorproject »Supernaturalis«",
    "category": "Design",
    "description": "Supernaturalis examines the absurd side of our thinking that shapes us all. Through rituals, lucky charms, amulets from different cultures as well as unusual archival finds and anecdotes, this human irrationality is expressed both in terms of content and design. Accompanying the book of curiosities, the extensible archive on Instagram offers a constantly growing collection and staging of contemporary lucky charms, allowing readers to question their own magical thinking.",
    "images": [
      "/projects/bachelorproject-supernaturalis/01-cover.jpg",
      "/projects/bachelorproject-supernaturalis/02-spread.jpg",
      "/projects/bachelorproject-supernaturalis/03-detail.jpg",
      "/projects/bachelorproject-supernaturalis/04-detail2.jpg",
      "/projects/bachelorproject-supernaturalis/05-detail3.jpg"
    ]
  },
  {
    "id": 2,
    "slug": "bionade-litschi",
    "title": "Bionade Litschi",
    "category": "Illustration",
    "description": "Label and packaging illustration for Bionade Litschi. The design features lush botanical motifs and playful typography, bringing the product identity to life through vibrant, hand-drawn elements.",
    "images": [
      "/projects/bionade-litschi/01-halsetikett.png",
      "/projects/bionade-litschi/02-bauchetikett.png"
    ]
  },
  {
    "id": 3,
    "slug": "cloud-associations",
    "title": "Poster Series »Cloud Associations«",
    "category": "Design",
    "description": "A poster series exploring the imaginative connections between cloud formations and everyday objects, combining photography with typographic play.",
    "images": [
      "/projects/cloud-associations/01-cover.jpg",
      "/projects/cloud-associations/02-poster1.jpg",
      "/projects/cloud-associations/03-poster2.jpg",
      "/projects/cloud-associations/04-wide.jpg",
      "/projects/cloud-associations/05-detail1.jpg",
      "/projects/cloud-associations/06-detail2.jpg",
      "/projects/cloud-associations/07-detail3.jpg"
    ]
  },
  {
    "id": 4,
    "slug": "event-branding-schraege-zaehne",
    "title": "Event Branding »Schräge Zähne«",
    "category": "Design",
    "description": "»Schräge Zähne« is an interdisciplinary performance bringing together young artists from a wide range of disciplines. The visual identity employs contrasting typefaces, flexible layout systems, and a visual language that embraces variety while maintaining coherence, allowing each discipline to find its own visual expression within a unified framework.",
    "images": [
      "/projects/event-branding-schraege-zaehne/01-cover.jpg",
      "/projects/event-branding-schraege-zaehne/02-poster.jpg",
      "/projects/event-branding-schraege-zaehne/03-merch.jpg",
      "/projects/event-branding-schraege-zaehne/04-detail1.jpg",
      "/projects/event-branding-schraege-zaehne/05-detail2.jpg"
    ]
  },
  {
    "id": 5,
    "slug": "illustrations",
    "title": "Illustrations",
    "category": "Illustration",
    "description": "A series of illustrations using bold colors and symbolic imagery to communicate complex social topics — from HPV awareness to psychology and right-wing extremism — in an accessible, visually engaging way.",
    "images": [
      "/projects/illustrations/01-hpv.png",
      "/projects/illustrations/02-psychologie.png",
      "/projects/illustrations/03-rechtsextremismus.png"
    ]
  },
  {
    "id": 6,
    "slug": "luckycharm-research",
    "title": "Luckycharm Research Project",
    "category": "Design",
    "description": "A research project exploring the cultural significance of lucky charms and talismans across different traditions, documented through careful visual cataloguing and design.",
    "images": [
      "/projects/luckycharm-research/01-cover.jpg",
      "/projects/luckycharm-research/02-detail.jpg",
      "/projects/luckycharm-research/03-spread1.jpg",
      "/projects/luckycharm-research/04-spread2.jpg",
      "/projects/luckycharm-research/05-detail2.jpg",
      "/projects/luckycharm-research/06-detail3.jpg",
      "/projects/luckycharm-research/07-detail4.jpg",
      "/projects/luckycharm-research/08-detail5.jpg"
    ]
  },
  {
    "id": 7,
    "slug": "poster-for-exhibition",
    "title": "Poster for Exhibition",
    "category": "Illustration",
    "description": "An expressive typographic poster exploring the concept of guilty pleasures through hand-lettering and energetic visual rhythm.",
    "images": [
      "/projects/poster-for-exhibition/01-poster.jpg"
    ]
  },
  {
    "id": 8,
    "slug": "screen-printing-portrait",
    "title": "Screen Printing Portrait",
    "category": "Design",
    "description": "An experimental portrait series and exhibition booklet created through screen printing techniques, exploring layered color and texture to capture personality and mood.",
    "images": [
      "/projects/screen-printing-portrait/01-cover.jpg",
      "/projects/screen-printing-portrait/02-booklet.jpg",
      "/projects/screen-printing-portrait/03-portrait.jpg",
      "/projects/screen-printing-portrait/04-detail2.jpg",
      "/projects/screen-printing-portrait/05-detail3.jpg",
      "/projects/screen-printing-portrait/06-detail4.jpg",
      "/projects/screen-printing-portrait/07-detail5.jpg",
      "/projects/screen-printing-portrait/08-detail6.jpg"
    ]
  },
  {
    "id": 9,
    "slug": "typeface-limbda",
    "title": "Typeface Design »Limbda«",
    "category": "Design",
    "description": "A custom typeface design balancing geometric structure with organic warmth, suitable for both display and editorial use.",
    "images": [
      "/projects/typeface-limbda/01-cover.jpg",
      "/projects/typeface-limbda/02-detail.jpg"
    ]
  },
  {
    "id": 10,
    "slug": "weihnachtskarte",
    "title": "Weihnachtskarte",
    "category": "Illustration",
    "description": "A festive winter landscape illustration with a dreamy, atmospheric quality, combining digital techniques with a hand-drawn sensibility.",
    "images": [
      "/projects/weihnachtskarte/01-card.png"
    ]
  }
];
